spring:
  application:
    name: mykakebo
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/kakebo}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate